# Hurricane Analysis

#### Overview

This project is slightly different than others you have encountered thus far. Instead of a step-by-step tutorial, this project contains a series of open-ended requirements which describe the project you'll be building. There are many possible ways to correctly fulfill all of these requirements, and you should expect to use the internet, Codecademy, and other resources when you encounter a problem that you cannot easily solve.

#### Project Goals

You will work to write several functions that organize and manipulate data about Category 5 Hurricanes, the strongest hurricanes as rated by their wind speed. Each one of these functions will use a number of parameters, conditionals, lists, dictionaries, string manipulation, and return statements.

> I didn't do that; I used pandas dataframes and series instead.
>
> And I skipped making functions in most of these

#### Prerequisites

In order to complete this project, you should have completed the Loops and Dictionaries sections of the [Learn Python 3 Course](https://www.codecademy.com/learn/learn-python-3). This content is also covered in the [Data Scientist Career Path](https://www.codecademy.com/learn/paths/data-science/).

## Project Requirements

1. Hurricanes, also known as cyclones or typhoons, are one of the most powerful forces of nature on Earth. Due to climate change caused by human activity, the number and intensity of hurricanes has risen, calling for better preparation by the many communities that are devastated by them. As a concerned environmentalist, you want to look at data about the most powerful hurricanes that have occured. 

   Begin by looking at the `damages` list. The list contains strings representing the total cost in USD(`$`) caused by `34` category 5 hurricanes (wind speeds $\ge$ 157 mph (252 km/h)) in the Atlantic region. For some of the hurricanes, damage data was not recorded (`"Damages not recorded"`), while the rest are written in the format `"Prefix-B/M"`, where `B` stands for billions (`1000000000`) and `M` stands for millions (`1000000`).
   
   Write a function that returns a new list of updated damages where the recorded data is converted to float values and the missing data is retained as `"Damages not recorded"`.
   
   Test your function with the data stored in `damages`.

In [7]:
# damages (USD($)) of hurricanes
damages = ['Damages not recorded', '100M', 'Damages not recorded', '40M',
          '27.9M', '5M', 'Damages not recorded', '306M', '2M', '65.8M',
          '326M', '60.3M', '208M', '1.42B', '25.4M', 'Damages not recorded',
          '1.54B', '1.24B', '7.1B', '10B', '26.5B', '6.2B', '5.37B', '23.3B',
          '1.01B', '125B', '12B', '29.4B', '1.76B', '720M', '15.1B', '64.8B',
          '91.6B', '25.1B']

# 1
# Update Recorded Damages
conversion = {"M": 1000000,
             "B": 1000000000}


def is_numeric(string):
    if string == "" or string.count('.') > 1:
        return False
    numerics = ['1','2','3','4','5','6','7','8','9','0', '.']
    for char in string:
        if char not in numerics:
            return False
    return True

# function to update damages
def try_to_get_float(cost):
    last_char = cost[-1]
    if last_char in conversion and is_numeric(cost[:-1]):
      return float(cost[:-1]) * conversion[last_char]
    elif is_numeric(cost):
      return float(cost)
    else:
      return cost

import pandas as pd

def fix_damages(damages_list):
    series = pd.Series(damages_list) 
    return list(series.map(try_to_get_float))

# test function by updating damages
damages = fix_damages(damages)
print(damages)

['Damages not recorded', 100000000.0, 'Damages not recorded', 40000000.0, 27900000.0, 5000000.0, 'Damages not recorded', 306000000.0, 2000000.0, 65800000.0, 326000000.0, 60300000.0, 208000000.0, 1420000000.0, 25400000.0, 'Damages not recorded', 1540000000.0, 1240000000.0, 7100000000.0, 10000000000.0, 26500000000.0, 6200000000.0, 5370000000.0, 23300000000.0, 1010000000.0, 125000000000.0, 12000000000.0, 29400000000.0, 1760000000.0, 720000000.0, 15100000000.0, 64800000000.0, 91600000000.0, 25100000000.0]

2. Additional data collected on the `34` strongest Atlantic hurricanes are provided in a series of lists. The data includes:
   - `names`: names of the hurricanes
   - `months`: months in which the hurricanes occurred
   - `years`: years in which the hurricanes occurred
   - `max_sustained_winds`: maximum sustained winds (miles per hour) of the hurricanes
   - `areas_affected`: list of different areas affected by each of the hurricanes
   - `deaths`: total number of deaths caused by each of the hurricanes
   
   The data is organized such that the data at each index, from `0` to `33`, corresponds to the same hurricane.
   
   For example, `names[0]` yields the "Cuba I" hurricane, which occurred in `months[0]` (October) `years[0]` (1924).
   
   Write a function that constructs a dictionary made out of the lists, where the keys of the dictionary are the names of the hurricanes, and the values are dictionaries themselves containing a key for each piece of data (`Name`, `Month`, `Year`, `Max Sustained Wind`, `Areas Affected`, `Damage`, `Death`) about the hurricane.
   
   Thus the key `"Cuba I"` would have the value: `{'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Deaths': 90}`.
   
   Test your function on the lists of data provided.

In [8]:
# names of hurricanes
names = ['Cuba I', 'San Felipe II Okeechobee', 'Bahamas', 'Cuba II', 'CubaBrownsville', 'Tampico', 'Labor Day', 'New England', 'Carol', 'Janet', 'Carla', 'Hattie', 'Beulah', 'Camille', 'Edith', 'Anita', 'David', 'Allen', 'Gilbert', 'Hugo', 'Andrew', 'Mitch', 'Isabel', 'Ivan', 'Emily', 'Katrina', 'Rita', 'Wilma', 'Dean', 'Felix', 'Matthew', 'Irma', 'Maria', 'Michael']

# months of hurricanes
months = ['October', 'September', 'September', 'November', 'August', 'September', 'September', 'September', 'September', 'September', 'September', 'October', 'September', 'August', 'September', 'September', 'August', 'August', 'September', 'September', 'August', 'October', 'September', 'September', 'July', 'August', 'September', 'October', 'August', 'September', 'October', 'September', 'September', 'October']

# years of hurricanes
years = [1924, 1928, 1932, 1932, 1933, 1933, 1935, 1938, 1953, 1955, 1961, 1961, 1967, 1969, 1971, 1977, 1979, 1980, 1988, 1989, 1992, 1998, 2003, 2004, 2005, 2005, 2005, 2005, 2007, 2007, 2016, 2017, 2017, 2018]

# maximum sustained winds (mph) of hurricanes
max_sustained_winds = [165, 160, 160, 175, 160, 160, 185, 160, 160, 175, 175, 160, 160, 175, 160, 175, 175, 190, 185, 160, 175, 180, 165, 165, 160, 175, 180, 185, 175, 175, 165, 180, 175, 160]

# areas affected by each hurricane
areas_affected = [['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], ['The Bahamas', 'Northeastern United States'], ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], ['The Bahamas', 'Cuba', 'Florida', 'Texas', 'Tamaulipas'], ['Jamaica', 'Yucatn Peninsula'], ['The Bahamas', 'Florida', 'Georgia', 'The Carolinas', 'Virginia'], ['Southeastern United States', 'Northeastern United States', 'Southwestern Quebec'], ['Bermuda', 'New England', 'Atlantic Canada'], ['Lesser Antilles', 'Central America'], ['Texas', 'Louisiana', 'Midwestern United States'], ['Central America'], ['The Caribbean', 'Mexico', 'Texas'], ['Cuba', 'United States Gulf Coast'], ['The Caribbean', 'Central America', 'Mexico', 'United States Gulf Coast'], ['Mexico'], ['The Caribbean', 'United States East coast'], ['The Caribbean', 'Yucatn Peninsula', 'Mexico', 'South Texas'], ['Jamaica', 'Venezuela', 'Central America', 'Hispaniola', 'Mexico'], ['The Caribbean', 'United States East Coast'], ['The Bahamas', 'Florida', 'United States Gulf Coast'], ['Central America', 'Yucatn Peninsula', 'South Florida'], ['Greater Antilles', 'Bahamas', 'Eastern United States', 'Ontario'], ['The Caribbean', 'Venezuela', 'United States Gulf Coast'], ['Windward Islands', 'Jamaica', 'Mexico', 'Texas'], ['Bahamas', 'United States Gulf Coast'], ['Cuba', 'United States Gulf Coast'], ['Greater Antilles', 'Central America', 'Florida'], ['The Caribbean', 'Central America'], ['Nicaragua', 'Honduras'], ['Antilles', 'Venezuela', 'Colombia', 'United States East Coast', 'Atlantic Canada'], ['Cape Verde', 'The Caribbean', 'British Virgin Islands', 'U.S. Virgin Islands', 'Cuba', 'Florida'], ['Lesser Antilles', 'Virgin Islands', 'Puerto Rico', 'Dominican Republic', 'Turks and Caicos Islands'], ['Central America', 'United States Gulf Coast (especially Florida Panhandle)']]

# damages (USD($)) of hurricanes
damages = ['Damages not recorded', '100M', 'Damages not recorded', '40M', '27.9M', '5M', 'Damages not recorded', '306M', '2M', '65.8M', '326M', '60.3M', '208M', '1.42B', '25.4M', 'Damages not recorded', '1.54B', '1.24B', '7.1B', '10B', '26.5B', '6.2B', '5.37B', '23.3B', '1.01B', '125B', '12B', '29.4B', '1.76B', '720M', '15.1B', '64.8B', '91.6B', '25.1B']

# deaths for each hurricane
deaths = [90,4000,16,3103,179,184,408,682,5,1023,43,319,688,259,37,11,2068,269,318,107,65,19325,51,124,17,1836,125,87,45,133,603,138,3057,74]

damages = fix_damages(damages)
# 2
# Create a Table
table = [names, months, years, max_sustained_winds, areas_affected, damages, deaths]


import pandas as pd

data = { 
  "Name": names, "Month": months, "Year": years, 
  "Max Sustained Wind": max_sustained_winds, 
  "Areas Affected": areas_affected, 
  "Damage": damages, "Deaths": deaths 
}

df = pd.DataFrame.from_dict(data, orient="columns")
df.set_axis(names, axis=0, inplace=True) # rename rows (indices)
df.head()

,Name,Month,Year,Max Sustained Wind,Areas Affected,Damage,Deaths
Cuba I,Cuba I,October,1924,165,"[Central America, Mexico, Cuba, Florida, The B...",Damages not recorded,90
San Felipe II Okeechobee,San Felipe II Okeechobee,September,1928,160,"[Lesser Antilles, The Bahamas, United States E...",1e+08,4000
Bahamas,Bahamas,September,1932,160,"[The Bahamas, Northeastern United States]",Damages not recorded,16
Cuba II,Cuba II,November,1932,175,"[Lesser Antilles, Jamaica, Cayman Islands, Cub...",4e+07,3103
CubaBrownsville,CubaBrownsville,August,1933,160,"[The Bahamas, Cuba, Florida, Texas, Tamaulipas]",2.79e+07,179

In [9]:
# Create and view the hurricanes dictionary
hurricane_info_by_name = df.to_dict(orient="index")
print(hurricane_info_by_name["Cuba I"])

{'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Deaths': 90}

In [10]:
df = pd.DataFrame.from_dict(hurricane_info_by_name, orient="index")
df.head()

,Name,Month,Year,Max Sustained Wind,Areas Affected,Damage,Deaths
Cuba I,Cuba I,October,1924,165,"[Central America, Mexico, Cuba, Florida, The B...",Damages not recorded,90
San Felipe II Okeechobee,San Felipe II Okeechobee,September,1928,160,"[Lesser Antilles, The Bahamas, United States E...",1e+08,4000
Bahamas,Bahamas,September,1932,160,"[The Bahamas, Northeastern United States]",Damages not recorded,16
Cuba II,Cuba II,November,1932,175,"[Lesser Antilles, Jamaica, Cayman Islands, Cub...",4e+07,3103
CubaBrownsville,CubaBrownsville,August,1933,160,"[The Bahamas, Cuba, Florida, Texas, Tamaulipas]",2.79e+07,179

3. In addition to organizing the hurricanes in a dictionary with names as the key, you want to be able to organize the hurricanes by year.

   Write a function that converts the current dictionary of hurricanes to a new dictionary, where the keys are years and the values are lists containing a dictionary for each hurricane that occurred in that year.
   
   For example, the key `1932` would yield the value: `[{'Name': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 'Damage not recorded', 'Deaths': 16}, {'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Deaths': 3103}]`.
   
   Test your function on your hurricane dictionary.

In [13]:
# 3
# Organizing by Year
result = df.set_index(["Year", "Name"], drop=False)
result.head()

                                                   Name      Month  Year  \
Year Name
1924 Cuba I                                      Cuba I    October  1924
1928 San Felipe II Okeechobee  San Felipe II Okeechobee  September  1928
1932 Bahamas                                    Bahamas  September  1932
     Cuba II                                    Cuba II   November  1932
1933 CubaBrownsville                    CubaBrownsville     August  1933

                               Max Sustained Wind  \
Year Name
1924 Cuba I                                   165
1928 San Felipe II Okeechobee                 160
1932 Bahamas                                  160
     Cuba II                                  175
1933 CubaBrownsville                          160

                                                                  Areas Affected  \
Year Name
1924 Cuba I                    [Central America, Mexico, Cuba, Florida, The B...
1928 San Felipe II Okeechobee  [Lesser Antilles, The Bahamas, United States E...
1932 Bahamas                           [The Bahamas, Northeastern United States]
     Cuba II                   [Lesser Antilles, Jamaica, Cayman Islands, Cub...
1933 CubaBrownsville             [The Bahamas, Cuba, Florida, Texas, Tamaulipas]

                                             Damage  Deaths
Year Name
1924 Cuba I                    Damages not recorded      90
1928 San Felipe II Okeechobee                 1e+08    4000
1932 Bahamas                   Damages not recorded      16
     Cuba II                                  4e+07    3103
1933 CubaBrownsville                       2.79e+07     179

In [14]:
# create a new dictionary of hurricanes with year and key
def make_dict_of_lists(dictionary):
    new_dict = dict()
    for key in dictionary:
        if isinstance(key, tuple):
            new_dict.setdefault(key[0], []).append({key[1] : dictionary[key]})
        else:
            new_dict[key] = dictionary[key]
    return new_dict

hurricanes_by_year = make_dict_of_lists(result.to_dict(orient="index"))
hurricanes_by_year[1932]

[{'Bahamas': {'Name': 'Bahamas',
   'Month': 'September',
   'Year': 1932,
   'Max Sustained Wind': 160,
   'Areas Affected': ['The Bahamas', 'Northeastern United States'],
   'Damage': 'Damages not recorded',
   'Deaths': 16}},
 {'Cuba II': {'Name': 'Cuba II',
   'Month': 'November',
   'Year': 1932,
   'Max Sustained Wind': 175,
   'Areas Affected': ['Lesser Antilles',
    'Jamaica',
    'Cayman Islands',
    'Cuba',
    'The Bahamas',
    'Bermuda'],
   'Damage': 40000000.0,
   'Deaths': 3103}}]

4. You believe that knowing how often each of the areas of the Atlantic are affected by these strong hurricanes is important for making preparations for future hurricanes.

   Write a function that counts how often each area is listed as an affected area of a hurricane. Store and return the results in a dictionary where the keys are the affected areas and the values are counts of how many times the areas were affected.
   
   Test your function on your hurricane dictionary.

In [15]:
# 4
# Counting Damaged Areas
set_of_locations = set()
for area in df["Areas Affected"]:
    set_of_locations.update(area)
set_of_locations

{'Antilles',
 'Atlantic Canada',
 'Bahamas',
 'Bermuda',
 'British Virgin Islands',
 'Cape Verde',
 'Cayman Islands',
 'Central America',
 'Colombia',
 'Cuba',
 'Dominican Republic',
 'Eastern United States',
 'Florida',
 'Georgia',
 'Greater Antilles',
 'Hispaniola',
 'Honduras',
 'Jamaica',
 'Lesser Antilles',
 'Louisiana',
 'Mexico',
 'Midwestern United States',
 'New England',
 'Nicaragua',
 'Northeastern United States',
 'Ontario',
 'Puerto Rico',
 'South Florida',
 'South Texas',
 'Southeastern United States',
 'Southwestern Quebec',
 'Tamaulipas',
 'Texas',
 'The Bahamas',
 'The Caribbean',
 'The Carolinas',
 'Turks and Caicos Islands',
 'U.S. Virgin Islands',
 'United States East Coast',
 'United States East coast',
 'United States Gulf Coast',
 'United States Gulf Coast (especially Florida Panhandle)',
 'Venezuela',
 'Virgin Islands',
 'Virginia',
 'Windward Islands',
 'Yucatn Peninsula'}

In [16]:
for location in set_of_locations:
    if location not in df.columns:
        df.insert(loc=len(df.columns), column=location, value=False)

for (row, areas) in df["Areas Affected"].items():
    for area in areas:
        if area in df.columns:
            df.loc[row, area] = True
        
df.head()

,Name,Month,Year,Max Sustained Wind,Areas Affected,Damage,Deaths,Yucatn Peninsula,Turks and Caicos Islands,British Virgin Islands,...,Lesser Antilles,Atlantic Canada,Hispaniola,Dominican Republic,Honduras,Virgin Islands,Virginia,Cape Verde,Eastern United States,Southwestern Quebec
Cuba I,Cuba I,October,1924,165,"[Central America, Mexico, Cuba, Florida, The B...",Damages not recorded,90,False,False,False,...,False,False,False,False,False,False,False,False,False,False
San Felipe II Okeechobee,San Felipe II Okeechobee,September,1928,160,"[Lesser Antilles, The Bahamas, United States E...",1e+08,4000,False,False,False,...,True,True,False,False,False,False,False,False,False,False
Bahamas,Bahamas,September,1932,160,"[The Bahamas, Northeastern United States]",Damages not recorded,16,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Cuba II,Cuba II,November,1932,175,"[Lesser Antilles, Jamaica, Cayman Islands, Cub...",4e+07,3103,False,False,False,...,True,False,False,False,False,False,False,False,False,False
CubaBrownsville,CubaBrownsville,August,1933,160,"[The Bahamas, Cuba, Florida, Texas, Tamaulipas]",2.79e+07,179,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [17]:
# create dictionary of areas to store the number of hurricanes involved in each area
area_was_hit = df[set_of_locations]
amount_of_hurricanes_in_area = area_was_hit.sum().to_dict()
amount_of_hurricanes_in_area

{'Yucatn Peninsula': 3,
 'Turks and Caicos Islands': 1,
 'British Virgin Islands': 1,
 'Bermuda': 2,
 'Nicaragua': 1,
 'Florida': 6,
 'Jamaica': 4,
 'Bahamas': 2,
 'The Carolinas': 1,
 'Ontario': 1,
 'South Florida': 1,
 'Central America': 9,
 'The Caribbean': 8,
 'United States Gulf Coast': 6,
 'Midwestern United States': 1,
 'Southeastern United States': 1,
 'United States East coast': 1,
 'Colombia': 1,
 'Tamaulipas': 1,
 'Windward Islands': 1,
 'Puerto Rico': 1,
 'New England': 1,
 'Greater Antilles': 2,
 'South Texas': 1,
 'United States East Coast': 3,
 'Cayman Islands': 1,
 'Texas': 4,
 'Venezuela': 3,
 'Antilles': 1,
 'The Bahamas': 7,
 'Cuba': 6,
 'Mexico': 7,
 'U.S. Virgin Islands': 1,
 'Georgia': 1,
 'Louisiana': 1,
 'Northeastern United States': 2,
 'United States Gulf Coast (especially Florida Panhandle)': 1,
 'Lesser Antilles': 4,
 'Atlantic Canada': 3,
 'Hispaniola': 1,
 'Dominican Republic': 1,
 'Honduras': 1,
 'Virgin Islands': 1,
 'Virginia': 1,
 'Cape Verde': 1,
 'Eastern United States': 1,
 'Southwestern Quebec': 1}


an attempt at doing the same thing by using python Count class is below

In [18]:
# 4
# Counting Damaged Areas
from collections import Counter
counts = Counter()

for areas_list in df["Areas Affected"]:
    counts.update(areas_list)
    
# create dictionary of areas to store the number of hurricanes involved there 
number_of_hurricanes_in_area = dict(counts)
number_of_hurricanes_in_area

{'Central America': 9,
 'Mexico': 7,
 'Cuba': 6,
 'Florida': 6,
 'The Bahamas': 7,
 'Lesser Antilles': 4,
 'United States East Coast': 3,
 'Atlantic Canada': 3,
 'Northeastern United States': 2,
 'Jamaica': 4,
 'Cayman Islands': 1,
 'Bermuda': 2,
 'Texas': 4,
 'Tamaulipas': 1,
 'Yucatn Peninsula': 3,
 'Georgia': 1,
 'The Carolinas': 1,
 'Virginia': 1,
 'Southeastern United States': 1,
 'Southwestern Quebec': 1,
 'New England': 1,
 'Louisiana': 1,
 'Midwestern United States': 1,
 'The Caribbean': 8,
 'United States Gulf Coast': 6,
 'United States East coast': 1,
 'South Texas': 1,
 'Venezuela': 3,
 'Hispaniola': 1,
 'South Florida': 1,
 'Greater Antilles': 2,
 'Bahamas': 2,
 'Eastern United States': 1,
 'Ontario': 1,
 'Windward Islands': 1,
 'Nicaragua': 1,
 'Honduras': 1,
 'Antilles': 1,
 'Colombia': 1,
 'Cape Verde': 1,
 'British Virgin Islands': 1,
 'U.S. Virgin Islands': 1,
 'Virgin Islands': 1,
 'Puerto Rico': 1,
 'Dominican Republic': 1,
 'Turks and Caicos Islands': 1,
 'United States Gulf Coast (especially Florida Panhandle)': 1}

In [30]:
df = pd.DataFrame.from_dict(hurricane_info_by_name, orient="index")
df.head()

,Name,Month,Year,Max Sustained Wind,Areas Affected,Damage,Deaths
Cuba I,Cuba I,October,1924,165,"[Central America, Mexico, Cuba, Florida, The B...",Damages not recorded,90
San Felipe II Okeechobee,San Felipe II Okeechobee,September,1928,160,"[Lesser Antilles, The Bahamas, United States E...",1e+08,4000
Bahamas,Bahamas,September,1932,160,"[The Bahamas, Northeastern United States]",Damages not recorded,16
Cuba II,Cuba II,November,1932,175,"[Lesser Antilles, Jamaica, Cayman Islands, Cub...",4e+07,3103
CubaBrownsville,CubaBrownsville,August,1933,160,"[The Bahamas, Cuba, Florida, Texas, Tamaulipas]",2.79e+07,179

5. Write a function that finds the area affected by the most hurricanes, and how often it was hit.

   Test your function on your affected area dictionary.

In [39]:
# 5
# Calculating Maximum Hurricane Count
def get_max(dictionary):
    # returns max as ordered pair (tuple)
    use_index_1 = lambda pair: pair[1] if isinstance(pair[1], (float, int)) else 0
    return max(dictionary.items(), key = use_index_1 )

# find most frequently affected area and the number of hurricanes involved in
most_hit = get_max(amount_of_hurricanes_in_area)
print(most_hit)
print("The region with the most hurricanes was {} with {} hurricanes".format(*most_hit))

('Central America', 9)
The region with the most hurricanes was Central America with 9 hurricanes

6. Write a function that finds the hurricane that caused the greatest number of deaths, and how many deaths it caused.

   Test your function on your hurricane dictionary.

In [24]:
# 6
# Calculating the Deadliest Hurricane

# find highest mortality hurricane and the number of deaths
deaths_series = df["Deaths"]
most_deadly = deaths_series.idxmax()
print((most_deadly, deaths_series[most_deadly]))
print("The deadliest hurricane was {deadliest} with {deaths} deaths.".format(deadliest=most_deadly, deaths=deaths_series[most_deadly]))

('Mitch', 19325)
The deadliest hurricanes was Mitch with 19325 hurricanes

7. Just as hurricanes are rated by their windspeed, you want to try rating hurricanes based on other metrics.

   Write a function that rates hurricanes on a mortality scale according to the following ratings, where the key is the rating and the value is the upper bound of deaths for that rating.
   
   ```py
   mortality_scale = {0: 0,
   1: 100,
   2: 500,
   3: 1000,
   4: 10000}
   ```
   
   For example, a hurricane with a `1` mortality rating would have resulted in greater than `0` but less than or equal to `100` deaths. A hurricane with a `5` mortality would have resulted in greater than `10000` deaths.
   
   Store the hurricanes in a new dictionary where the keys are the mortaility ratings and the values are lists containing a dictionary for each hurricane that falls into that mortality rating.
   
   Test your function on your hurricane dictionary.

In [33]:
# 7
# Rating Hurricanes by Mortality
mortality_scale = {
    0: 0,
    1: 100,
    2: 500,
    3: 1000,
    4: 10000
}

def get_rating(schedule_dict, value):
    keys = schedule_dict.keys() if isinstance(schedule_dict, dict) else range(len(schedule_dict))
    if not isinstance(value, (float, int)):
        return 0
    i = 0
    while i in keys:
        if(value <= schedule_dict[i]):
            return i
        i += 1
    return i

# categorize hurricanes in new dictionary with mortality severity as key
df["Mortality Category"] = df["Deaths"].apply(lambda mortality: get_rating(mortality_scale, mortality))
#print(df["Mortality Category"])
result = df.set_index(["Mortality Category","Name"], drop=False)
result.head()

,,Name,Month,Year,Max Sustained Wind,Areas Affected,Damage,Deaths,Mortality Category
Mortality Category,Name,,,,,,,,
1,Cuba I,Cuba I,October,1924,165,"[Central America, Mexico, Cuba, Florida, The B...",Damages not recorded,90,1
4,San Felipe II Okeechobee,San Felipe II Okeechobee,September,1928,160,"[Lesser Antilles, The Bahamas, United States E...",1e+08,4000,4
1,Bahamas,Bahamas,September,1932,160,"[The Bahamas, Northeastern United States]",Damages not recorded,16,1
4,Cuba II,Cuba II,November,1932,175,"[Lesser Antilles, Jamaica, Cayman Islands, Cub...",4e+07,3103,4
2,CubaBrownsville,CubaBrownsville,August,1933,160,"[The Bahamas, Cuba, Florida, Texas, Tamaulipas]",2.79e+07,179,2

In [35]:
   # make_dict_of_lists function was defined earlier
hurricanes_by_mortality_rating = make_dict_of_lists(result.to_dict(orient="index"))
hurricanes_by_mortality_rating[5]

[{'Mitch': {'Name': 'Mitch',
   'Month': 'October',
   'Year': 1998,
   'Max Sustained Wind': 180,
   'Areas Affected': ['Central America', 'Yucatn Peninsula', 'South Florida'],
   'Damage': 6200000000.0,
   'Deaths': 19325,
   'Mortality Category': 5}}]

In [36]:
df = pd.DataFrame.from_dict(hurricane_info_by_name, orient="index")
df.head()

,Name,Month,Year,Max Sustained Wind,Areas Affected,Damage,Deaths
Cuba I,Cuba I,October,1924,165,"[Central America, Mexico, Cuba, Florida, The B...",Damages not recorded,90
San Felipe II Okeechobee,San Felipe II Okeechobee,September,1928,160,"[Lesser Antilles, The Bahamas, United States E...",1e+08,4000
Bahamas,Bahamas,September,1932,160,"[The Bahamas, Northeastern United States]",Damages not recorded,16
Cuba II,Cuba II,November,1932,175,"[Lesser Antilles, Jamaica, Cayman Islands, Cub...",4e+07,3103
CubaBrownsville,CubaBrownsville,August,1933,160,"[The Bahamas, Cuba, Florida, Texas, Tamaulipas]",2.79e+07,179

8. Write a function that finds the hurricane that caused the greatest damage, and how costly it was.

   Test your function on your hurricane dictionary.

In [41]:
# 8
# Calculating Hurricane Maximum Damage

# find highest damage inducing hurricane and its total cost
damages_series = df["Damage"]
most_costly = get_max(damages_series) # get_max was defined earlier, returns ordered pair (tuple)
print(most_costly)
print("The hurricanes with the greatest monetary cost was {costliest} with {cost} in damages.".format(costliest=most_costly[0], cost=most_costly[1]))

('Katrina', 125000000000.0)
The hurricanes with the greatest monetary cost was Katrina with 125000000000.0 in damages.

9. Lastly, you want to rate hurricanes according to how much damage they cause.

   Write a function that rates hurricanes on a damage scale according to the following ratings, where the key is the rating and the value is the upper bound of damage for that rating.
   ```py
   damage_scale = {0: 0,
   1: 100000000,
   2: 1000000000,
   3: 10000000000,
   4: 50000000000}
   ```
   
   For example, a hurricane with a `1` damage rating would have resulted in damages greater than `0` USD but less than or equal to `100000000` USD. A hurricane with a `5` damage rating would have resulted in damages greater than `50000000000` USD (talk about a lot of money).
   
   Store the hurricanes in a new dictionary where the keys are damage ratings and the values are lists containing a dictionary for each hurricane that falls into that damage rating.
   
   Test your function on your hurricane dictionary.

In [43]:
# 9
# Rating Hurricanes by Damage
damage_scale = {0: 0,
                1: 100000000,
                2: 1000000000,
                3: 10000000000,
                4: 50000000000}

# categorize hurricanes in new dictionary with damage severity as key
df["Damage Category"] = df["Damage"].apply(lambda damage: get_rating(damage_scale, damage))
#print(df["Damage Category"])
result = df.set_index(["Damage Category","Name"], drop=False)
result.head()

                                                              Name      Month  \
Damage Category Name
0               Cuba I                                      Cuba I    October
1               San Felipe II Okeechobee  San Felipe II Okeechobee  September
0               Bahamas                                    Bahamas  September
1               Cuba II                                    Cuba II   November
                CubaBrownsville                    CubaBrownsville     August

                                          Year  Max Sustained Wind  \
Damage Category Name
0               Cuba I                    1924                 165
1               San Felipe II Okeechobee  1928                 160
0               Bahamas                   1932                 160
1               Cuba II                   1932                 175
                CubaBrownsville           1933                 160

                                                                             Areas Affected  \
Damage Category Name
0               Cuba I                    [Central America, Mexico, Cuba, Florida, The B...
1               San Felipe II Okeechobee  [Lesser Antilles, The Bahamas, United States E...
0               Bahamas                           [The Bahamas, Northeastern United States]
1               Cuba II                   [Lesser Antilles, Jamaica, Cayman Islands, Cub...
                CubaBrownsville             [The Bahamas, Cuba, Florida, Texas, Tamaulipas]

                                                        Damage  Deaths  \
Damage Category Name
0               Cuba I                    Damages not recorded      90
1               San Felipe II Okeechobee                 1e+08    4000
0               Bahamas                   Damages not recorded      16
1               Cuba II                                  4e+07    3103
                CubaBrownsville                       2.79e+07     179

                                          Damage Category
Damage Category Name
0               Cuba I                                  0
1               San Felipe II Okeechobee                1
0               Bahamas                                 0
1               Cuba II                                 1
                CubaBrownsville                         1

In [44]:
   # make_dict_of_lists function was defined earlier
hurricanes_by_damage_rating = make_dict_of_lists(result.to_dict(orient="index"))
hurricanes_by_damage_rating[5]

[{'Katrina': {'Name': 'Katrina',
   'Month': 'August',
   'Year': 2005,
   'Max Sustained Wind': 175,
   'Areas Affected': ['Bahamas', 'United States Gulf Coast'],
   'Damage': 125000000000.0,
   'Deaths': 1836,
   'Damage Category': 5}},
 {'Irma': {'Name': 'Irma',
   'Month': 'September',
   'Year': 2017,
   'Max Sustained Wind': 180,
   'Areas Affected': ['Cape Verde',
    'The Caribbean',
    'British Virgin Islands',
    'U.S. Virgin Islands',
    'Cuba',
    'Florida'],
   'Damage': 64800000000.0,
   'Deaths': 138,
   'Damage Category': 5}},
 {'Maria': {'Name': 'Maria',
   'Month': 'September',
   'Year': 2017,
   'Max Sustained Wind': 175,
   'Areas Affected': ['Lesser Antilles',
    'Virgin Islands',
    'Puerto Rico',
    'Dominican Republic',
    'Turks and Caicos Islands'],
   'Damage': 91600000000.0,
   'Deaths': 3057,
   'Damage Category': 5}}]

## Solution

Great work! View the **Hurricane Analysis_Solution.ipynb** file or visit [our forums](https://discuss.codecademy.com/t/hurricane-analysis-challenge-project-python/462363) to compare your project to our sample solution code. You can also learn how to host your own solution on GitHub so you can share it with other learners! Your solution might look different than ours, and that's okay! There are multiple ways to solve these projects, and you'll learn more by seeing others' code.

In [45]:
print("done!")

done!